sudo: required
services:
  - docker

before_install:
  - docker build -t adeshadk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adeshadk/react-test npm test -- --coverage 

after_success:
  - docker build -t adeshadk/multi-client ./client
  - docker build -t adeshadk/multi-nginx ./nginx
  - docker build -t adeshadk/multi-server ./server
  - docker build -t adeshadk/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker
  - docker push adeshadk/multi-client
  - docker push adeshadk/multi-nginx 
  - docker push adeshadk/multi-server 
  - docker push adeshadk/multi-worker 
deply:
  provider: easticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-685919621674
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY